yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@pixi/tilemap@*":
    dependencies:
      "@pixi/canvas-renderer": "*"
      "@pixi/constants": "*"
      "@pixi/core": "*"
      "@pixi/display": "*"
      "@pixi/graphics": "*"
      "@pixi/math": "*"
      "@pixi/utils": "*"
